package rv32i

import "riscvasm.com/m/v2/instruction"

var Instructions = map[string]instruction.InstructionDefinition{
	"lui":       lui,
	"auipc":     auipc,
	"jal":       jal,
	"jalr":      jalr,
	"beq":       beq,
	"bne":       bne,
	"blt":       blt,
	"bge":       bge,
	"bltu":      bltu,
	"bgeu":      bgeu,
	"lb":        lb,
	"lh":        lh,
	"lw":        lw,
	"lbu":       lbu,
	"lhu":       lhu,
	"sb":        sb,
	"sh":        sh,
	"sw":        sw,
	"addi":      addi,
	"slti":      slti,
	"sltiu":     sltiu,
	"xori":      xori,
	"ori":       ori,
	"andi":      andi,
	"slli":      slli,
	"srli":      srli,
	"srai":      srai,
	"add":       add,
	"sub":       sub,
	"sll":       sll,
	"slt":       slt,
	"sltu":      sltu,
	"xor":       xor,
	"srl":       srl,
	"sra":       sra,
	"or":        or,
	"and":       and,
	"fence":     fence,
	"fence.tso": fence_tso,
	"pause":     pause,
	"ecall":     ecall,
	"ebreak":    ebreak,
}
